### ISSUE TITLE
Tutorial or requirements to compile our own tweaks or port others

### ISSUE THREAD

**Issue by JJGadgets** [iMokhles/Tweaks-for-SideLoaded-Apps#3]
I would like a list of steps and/or at least a requirements list on how to compile our own tweaks or port other existing ones. 

Also, can we modify tweak dylib's from Cydia and port them for TweakApp? I kinda want Cercube 3 for example.

**Comment by onesentinel** [comment]
If you really need some help I prob. could help you somewhere. I'm also in the learning mode, and trying to figure out how things works but I already know at least how most of it works
